require('dotenv').config();
const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
const { z } = require('zod');
const store = require('./db');
const { hashPassword, verifyPassword, signToken, requireAuth, requireRole } = require('./auth');
const { isInsideGeofence, calculateAllowedReturn, addMinutesIso, diffMinutesLate } = require('./geo');
const { calculateAndStoreCommission } = require('./money');

store.load();
const app = express();
app.use(cors()); app.use(express.json({ limit: '8mb' })); app.use(morgan('dev'));
const ok = (res, data={}) => res.json({ ok: true, ...data });
const now = () => new Date().toISOString();
const d = () => store.get();
function parse(schema, req, res) { const p=schema.safeParse(req.body); if(!p.success){res.status(400).json({error:'Validation error', details:p.error.flatten()}); return null;} return p.data; }
function driverByUser(userId) { return d().drivers.find(x => Number(x.user_id) === Number(userId)); }
function driverView(driver) { const user=d().users.find(u=>u.id===driver.user_id); return { ...driver, name:user?.name, phone:user?.phone }; }
function orderView(order) { const driver=order.driver_id ? d().drivers.find(x=>x.id===order.driver_id) : null; const user=driver ? d().users.find(u=>u.id===driver.user_id) : null; return { ...order, driver_name:user?.name || null }; }
function reportForDriver(driverId, date) {
  const start = new Date(`${date}T00:00:00.000Z`), end = new Date(`${date}T23:59:59.999Z`);
  const orders = d().orders.filter(o => Number(o.driver_id) === Number(driverId) && o.delivered_at && new Date(o.delivered_at) >= start && new Date(o.delivered_at) <= end).map(order => ({ ...order, ...(d().commissions.find(c=>Number(c.order_id)===Number(order.id)) || {}) }));
  const penalties = d().penalties.filter(p => Number(p.driver_id) === Number(driverId) && new Date(p.starts_at) >= start && new Date(p.starts_at) <= end);
  const totals = orders.reduce((a,o)=>{ a.order_count++; a.total_food_price += +o.food_price||0; a.total_delivery_fee += +o.delivery_fee||0; if(o.payment_method==='cash'){ a.total_cash_collected += +o.total_price||0; a.expected_return_to_restaurant += +o.total_price||0; } a.gross_driver_commission += +(o.base_commission||0); a.total_penalty_reduction += +(o.penalty_reduction||0); a.final_driver_commission += +(o.driver_commission_final||0); return a; }, { order_count:0,total_food_price:0,total_delivery_fee:0,total_cash_collected:0,expected_return_to_restaurant:0,gross_driver_commission:0,total_penalty_reduction:0,final_driver_commission:0 });
  totals.penalty_count = penalties.length;
  totals.total_penalty_minutes = penalties.reduce((s,p)=>s+Math.ceil((new Date(p.ends_at)-new Date(p.starts_at))/60000),0);
  return { date, totals, orders, penalties };
}
function ensureDriver(req, res) { const driver = driverByUser(req.user.id); if(!driver){res.status(403).json({error:'Driver profile not found'}); return null;} return driver; }

app.get('/health', (_,res)=>ok(res,{status:'healthy', dbPath:store.dbPath, time:now()}));
app.post('/auth/login', (req,res)=>{ const body=parse(z.object({phone:z.string(),password:z.string()}),req,res); if(!body)return; const user=d().users.find(u=>u.phone===body.phone); if(!user||!verifyPassword(body.password,user.password_hash)) return res.status(401).json({error:'Wrong phone or password'}); ok(res,{token:signToken(user), user:{id:user.id,role:user.role,name:user.name,phone:user.phone}, driver:user.role==='driver'?driverByUser(user.id):null}); });
app.get('/me', requireAuth, (req,res)=>{ const driver=req.user.role==='driver'?driverByUser(req.user.id):null; const latestConsent=driver?d().consents.filter(c=>c.driver_id===driver.id).sort((a,b)=>new Date(b.accepted_at)-new Date(a.accepted_at))[0] || null:null; ok(res,{user:req.user, driver, latestConsent}); });

app.post('/driver/consent', requireAuth, requireRole('driver'), (req,res)=>{ const driver=ensureDriver(req,res); if(!driver)return; const body=parse(z.object({trackingAccepted:z.boolean(),cameraAccepted:z.boolean(),backgroundTrackingAccepted:z.boolean(),policyVersion:z.string().default('1.0'),acceptedText:z.string().min(10)}),req,res); if(!body)return; const consent=store.insert('consents',{driver_id:driver.id,tracking_accepted:body.trackingAccepted?1:0,camera_accepted:body.cameraAccepted?1:0,background_tracking_accepted:body.backgroundTrackingAccepted?1:0,policy_version:body.policyVersion,accepted_text:body.acceptedText,accepted_at:now()}); store.update('drivers',driver.id,{tracking_enabled:body.trackingAccepted?1:0}); store.audit(req.user,'ACCEPT_CONSENT','driver',driver.id,null,consent); ok(res,{consent}); });

app.get('/restaurant/settings', requireAuth, requireRole('restaurant_admin','restaurant_staff'), (req,res)=>ok(res,{settings:d().settings}));
app.put('/restaurant/settings', requireAuth, requireRole('restaurant_admin'), (req,res)=>{ const old={...d().settings}; const allowed=['restaurant_name','restaurant_lat','restaurant_lng','geofence_radius_meters','average_return_speed_kmh','return_buffer_minutes','minimum_return_minutes','commission_type','fixed_commission_amount','commission_delivery_fee_percent','daily_salary_amount','per_order_commission_amount','penalty_enabled','auto_penalty_enabled','penalty_percent','penalty_duration_minutes','require_manager_approval_for_penalty']; for(const k of allowed){ if(req.body[k]!==undefined) d().settings[k]=req.body[k]; } d().settings.updated_at=now(); store.save(); store.audit(req.user,'UPDATE_SETTINGS','restaurant_settings',1,old,d().settings); ok(res,{settings:d().settings}); });

app.post('/restaurant/drivers', requireAuth, requireRole('restaurant_admin'), (req,res)=>{ const body=parse(z.object({name:z.string().min(2),phone:z.string().min(3),password:z.string().min(3),vehicle_type:z.string().optional()}),req,res); if(!body)return; if(d().users.some(u=>u.phone===body.phone)) return res.status(400).json({error:'Phone already exists'}); const user=store.insert('users',{role:'driver',name:body.name,phone:body.phone,password_hash:hashPassword(body.password),is_active:1}); const driver=store.insert('drivers',{user_id:user.id,status:'offline',vehicle_type:body.vehicle_type||'motorcycle',last_lat:null,last_lng:null,last_location_at:null,tracking_enabled:0}); store.audit(req.user,'CREATE_DRIVER','driver',driver.id,null,{...driver,name:user.name,phone:user.phone}); ok(res,{driver:driverView(driver)}); });
app.get('/restaurant/drivers', requireAuth, requireRole('restaurant_admin','restaurant_staff'), (_,res)=>ok(res,{drivers:d().drivers.map(driverView)}));
app.get('/restaurant/live-map', requireAuth, requireRole('restaurant_admin','restaurant_staff'), (_,res)=>ok(res,{settings:d().settings, drivers:d().drivers.map(driverView)}));

app.post('/restaurant/orders', requireAuth, requireRole('restaurant_admin','restaurant_staff'), (req,res)=>{ const body=parse(z.object({customer_name:z.string().min(2),customer_phone:z.string().optional(),customer_lat:z.number(),customer_lng:z.number(),customer_address:z.string().optional(),food_price:z.number().int().min(0),delivery_fee:z.number().int().min(0),payment_method:z.enum(['cash','card','prepaid','debt']).default('cash')}),req,res); if(!body)return; const order=store.insert('orders',{...body,total_price:body.food_price+body.delivery_fee,status:'new',driver_id:null,assigned_at:null,picked_up_at:null,arrived_customer_at:null,delivered_at:null,allowed_return_minutes:null,allowed_return_by:null,returned_at:null,proof_photo_path:null,proof_note:null,return_distance_km:null,late_minutes:0,created_by:req.user.id,updated_at:now()}); store.audit(req.user,'CREATE_ORDER','order',order.id,null,order); ok(res,{order:orderView(order)}); });
app.get('/restaurant/orders', requireAuth, requireRole('restaurant_admin','restaurant_staff'), (req,res)=>{ let orders=[...d().orders]; if(req.query.status) orders=orders.filter(o=>o.status===req.query.status); orders.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)); ok(res,{orders:orders.map(orderView)}); });
app.post('/restaurant/orders/:id/assign', requireAuth, requireRole('restaurant_admin','restaurant_staff'), (req,res)=>{ const body=parse(z.object({driver_id:z.number().int()}),req,res); if(!body)return; const order=d().orders.find(o=>o.id==req.params.id); const driver=d().drivers.find(x=>x.id==body.driver_id); if(!order)return res.status(404).json({error:'Order not found'}); if(!driver)return res.status(404).json({error:'Driver not found'}); const old={...order}; const updated=store.update('orders',order.id,{driver_id:driver.id,status:'assigned',assigned_at:now()}); store.update('drivers',driver.id,{status:'assigned'}); store.audit(req.user,'ASSIGN_ORDER','order',order.id,old,updated); ok(res,{order:orderView(updated)}); });

app.post('/driver/location', requireAuth, requireRole('driver'), (req,res)=>{ const driver=ensureDriver(req,res); if(!driver)return; const body=parse(z.object({lat:z.number(),lng:z.number(),accuracy_meters:z.number().optional(),speed_mps:z.number().optional(),provider:z.string().optional()}),req,res); if(!body)return; const loc=store.insert('driver_locations',{driver_id:driver.id,...body,recorded_at:now()}); const updated=store.update('drivers',driver.id,{last_lat:body.lat,last_lng:body.lng,last_location_at:loc.recorded_at}); ok(res,{driver:updated}); });
app.get('/driver/tasks', requireAuth, requireRole('driver'), (req,res)=>{ const driver=ensureDriver(req,res); if(!driver)return; const orders=d().orders.filter(o=>Number(o.driver_id)===Number(driver.id) && !['returned','cancelled'].includes(o.status)).map(orderView); ok(res,{driver,settings:d().settings,orders}); });
app.post('/driver/orders/:id/pickup', requireAuth, requireRole('driver'), (req,res)=>{ const driver=ensureDriver(req,res); if(!driver)return; const order=d().orders.find(o=>o.id==req.params.id&&o.driver_id===driver.id); if(!order)return res.status(404).json({error:'Order not found for this driver'}); const updated=store.update('orders',order.id,{status:'picked_up',picked_up_at:now()}); store.update('drivers',driver.id,{status:'picked_up'}); ok(res,{order:orderView(updated)}); });
app.post('/driver/orders/:id/arrive', requireAuth, requireRole('driver'), (req,res)=>{ const driver=ensureDriver(req,res); if(!driver)return; const order=d().orders.find(o=>o.id==req.params.id&&o.driver_id===driver.id); if(!order)return res.status(404).json({error:'Order not found for this driver'}); const updated=store.update('orders',order.id,{status:'arrived_customer',arrived_customer_at:now()}); store.update('drivers',driver.id,{status:'arrived_customer'}); ok(res,{order:orderView(updated)}); });
app.post('/driver/orders/:id/deliver', requireAuth, requireRole('driver'), (req,res)=>{ const driver=ensureDriver(req,res); if(!driver)return; const body=parse(z.object({proof_photo_path:z.string().optional(),proof_note:z.string().optional()}),req,res); if(!body)return; const order=d().orders.find(o=>o.id==req.params.id&&o.driver_id===driver.id); if(!order)return res.status(404).json({error:'Order not found for this driver'}); const settings=d().settings; const at=now(); const allowed=calculateAllowedReturn({customerLat:order.customer_lat,customerLng:order.customer_lng,restaurantLat:settings.restaurant_lat,restaurantLng:settings.restaurant_lng,averageReturnSpeedKmh:settings.average_return_speed_kmh,returnBufferMinutes:settings.return_buffer_minutes,minimumReturnMinutes:settings.minimum_return_minutes}); const updated=store.update('orders',order.id,{status:'returning',delivered_at:at,allowed_return_minutes:allowed.allowedReturnMinutes,allowed_return_by:addMinutesIso(at,allowed.allowedReturnMinutes),return_distance_km:allowed.distanceKm,proof_photo_path:body.proof_photo_path||null,proof_note:body.proof_note||null}); store.update('drivers',driver.id,{status:'delivered_returning'}); calculateAndStoreCommission(order.id); ok(res,{order:orderView(updated),allowedReturn:allowed}); });
app.post('/driver/orders/:id/return', requireAuth, requireRole('driver'), (req,res)=>{ const driver=ensureDriver(req,res); if(!driver)return; const body=parse(z.object({lat:z.number(),lng:z.number()}),req,res); if(!body)return; const order=d().orders.find(o=>o.id==req.params.id&&o.driver_id===driver.id); if(!order)return res.status(404).json({error:'Order not found for this driver'}); if(!order.allowed_return_by)return res.status(400).json({error:'Order not delivered yet'}); const s=d().settings; if(!isInsideGeofence(body.lat,body.lng,s.restaurant_lat,s.restaurant_lng,s.geofence_radius_meters)) return res.status(400).json({error:'Driver is not inside restaurant geofence',geofence_radius_meters:s.geofence_radius_meters}); const actual=now(); const late=diffMinutesLate(order.allowed_return_by,actual); const updated=store.update('orders',order.id,{status:'returned',returned_at:actual,late_minutes:late}); store.update('drivers',driver.id,{status:late>0?'late_return':'returned'}); let penalty=null; if(late>0 && s.penalty_enabled){ const starts_at=actual, ends_at=addMinutesIso(actual,s.penalty_duration_minutes); const status=(s.auto_penalty_enabled && !s.require_manager_approval_for_penalty)?'active':'pending'; penalty=store.insert('penalties',{driver_id:driver.id,order_id:order.id,reason:`Late return after delivery by ${late} minutes`,late_minutes:late,penalty_percent:s.penalty_percent,starts_at,ends_at,status,approved_by:null,created_by:req.user.id}); } store.audit(req.user,'RETURN_TO_RESTAURANT','order',order.id,order,{late,penalty}); ok(res,{order:orderView(updated),late_minutes:late,penalty}); });

app.get('/restaurant/penalties', requireAuth, requireRole('restaurant_admin','restaurant_staff'), (_,res)=>{ const penalties=d().penalties.map(p=>({...p,driver_name:driverView(d().drivers.find(x=>x.id===p.driver_id)||{}).name})).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)); ok(res,{penalties}); });
app.post('/restaurant/penalties/:id/approve', requireAuth, requireRole('restaurant_admin'), (req,res)=>{ const p=d().penalties.find(x=>x.id==req.params.id); if(!p)return res.status(404).json({error:'Penalty not found'}); const updated=store.update('penalties',p.id,{status:'active',approved_by:req.user.id}); store.update('drivers',p.driver_id,{status:'under_penalty'}); store.audit(req.user,'APPROVE_PENALTY','penalty',p.id,p,updated); ok(res,{penalty:updated}); });
app.post('/restaurant/penalties/manual', requireAuth, requireRole('restaurant_admin'), (req,res)=>{ const body=parse(z.object({driver_id:z.number().int(),reason:z.string().min(3),penalty_percent:z.number().min(0).max(100).default(50),duration_minutes:z.number().int().min(1).max(1440).default(60)}),req,res); if(!body)return; const driver=d().drivers.find(x=>x.id==body.driver_id); if(!driver)return res.status(404).json({error:'Driver not found'}); const starts_at=now(); const p=store.insert('penalties',{driver_id:driver.id,order_id:null,reason:body.reason,late_minutes:0,penalty_percent:body.penalty_percent,starts_at,ends_at:addMinutesIso(starts_at,body.duration_minutes),status:'active',approved_by:req.user.id,created_by:req.user.id}); store.update('drivers',driver.id,{status:'under_penalty'}); store.audit(req.user,'CREATE_MANUAL_PENALTY','penalty',p.id,null,p); ok(res,{penalty:p}); });
app.get('/driver/penalties', requireAuth, requireRole('driver'), (req,res)=>{ const driver=ensureDriver(req,res); if(!driver)return; ok(res,{penalties:d().penalties.filter(p=>p.driver_id===driver.id).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))}); });

app.get('/driver/report', requireAuth, requireRole('driver'), (req,res)=>{ const driver=ensureDriver(req,res); if(!driver)return; ok(res,{report:reportForDriver(driver.id, req.query.date || new Date().toISOString().slice(0,10))}); });
app.get('/restaurant/drivers/:id/report', requireAuth, requireRole('restaurant_admin','restaurant_staff'), (req,res)=>ok(res,{report:reportForDriver(Number(req.params.id), req.query.date || new Date().toISOString().slice(0,10))}));
app.post('/restaurant/settlements/:driverId/close', requireAuth, requireRole('restaurant_admin'), (req,res)=>{ const body=parse(z.object({date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),amount_returned_by_driver:z.number().int().min(0)}),req,res); if(!body)return; const report=reportForDriver(Number(req.params.driverId),body.date); const remaining=Math.max(0,report.totals.expected_return_to_restaurant-body.amount_returned_by_driver); const existing=d().settlements.find(s=>s.driver_id==req.params.driverId&&s.settlement_date===body.date); const payload={driver_id:Number(req.params.driverId),settlement_date:body.date,...report.totals,amount_returned_by_driver:body.amount_returned_by_driver,remaining_on_driver:remaining,created_by:req.user.id}; const settlement=existing?store.update('settlements',existing.id,payload):store.insert('settlements',payload); store.audit(req.user,'CLOSE_SETTLEMENT','settlement',settlement.id,null,settlement); ok(res,{settlement,report}); });
app.get('/restaurant/settlements', requireAuth, requireRole('restaurant_admin','restaurant_staff'), (req,res)=>{ const date=req.query.date || new Date().toISOString().slice(0,10); ok(res,{settlements:d().settlements.filter(s=>s.settlement_date===date).map(s=>({...s,driver_name:driverView(d().drivers.find(x=>x.id===s.driver_id)||{}).name}))}); });
app.get('/restaurant/audit-logs', requireAuth, requireRole('restaurant_admin'), (_,res)=>ok(res,{logs:d().audit_logs.slice().reverse().slice(0,300)}));

app.use((err,req,res,next)=>{ console.error(err); res.status(500).json({error:'Internal server error',details:process.env.NODE_ENV==='development'?err.message:undefined}); });
const port=Number(process.env.PORT||8080); if(require.main===module) app.listen(port,()=>console.log(`Delivery backend running on http://localhost:${port}`)); module.exports=app;
