import 'package:flutter/material.dart';
import '../models/app_models.dart';
import '../services/api_service.dart';

class OrdersScreen extends StatefulWidget{final ApiService api; const OrdersScreen({super.key,required this.api}); @override State<OrdersScreen> createState()=>_OrdersScreenState();}
class _OrdersScreenState extends State<OrdersScreen>{List<OrderRow> orders=[]; List<DriverRow> drivers=[]; bool loading=true;
 @override void initState(){super.initState(); load();}
 Future<void> load()async{final o=await widget.api.orders(); final d=await widget.api.drivers(); setState((){orders=(o['orders'] as List).map((e)=>OrderRow.fromJson(Map<String,dynamic>.from(e))).toList(); drivers=(d['drivers'] as List).map((e)=>DriverRow.fromJson(Map<String,dynamic>.from(e))).toList(); loading=false;});}
 Future<void> createOrder()async{final name=TextEditingController(); final phone=TextEditingController(); final address=TextEditingController(); final lat=TextEditingController(text:'31.0602'); final lng=TextEditingController(text:'46.2471'); final food=TextEditingController(text:'20000'); final delivery=TextEditingController(text:'3000'); await showDialog(context:context,builder:(c)=>AlertDialog(title:const Text('إضافة طلب'),content:SingleChildScrollView(child:Column(children:[TextField(controller:name,decoration:const InputDecoration(labelText:'اسم الزبون')),TextField(controller:phone,decoration:const InputDecoration(labelText:'الهاتف')),TextField(controller:address,decoration:const InputDecoration(labelText:'العنوان')),TextField(controller:lat,decoration:const InputDecoration(labelText:'Lat')),TextField(controller:lng,decoration:const InputDecoration(labelText:'Lng')),TextField(controller:food,decoration:const InputDecoration(labelText:'سعر الطلب')),TextField(controller:delivery,decoration:const InputDecoration(labelText:'أجرة التوصيل'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('إلغاء')),FilledButton(onPressed:()async{await widget.api.createOrder({'customer_name':name.text,'customer_phone':phone.text,'customer_address':address.text,'customer_lat':double.parse(lat.text),'customer_lng':double.parse(lng.text),'food_price':int.parse(food.text),'delivery_fee':int.parse(delivery.text),'payment_method':'cash'}); if(c.mounted)Navigator.pop(c);},child:const Text('حفظ'))])); await load();}
 Future<void> assign(OrderRow order)async{int? driverId=drivers.isEmpty?null:drivers.first.id; await showDialog(context:context,builder:(c)=>AlertDialog(title:Text('تعيين طلب #${order.id}'),content:DropdownButtonFormField<int>(value:driverId,items:drivers.map((d)=>DropdownMenuItem(value:d.id,child:Text('${d.name} - ${d.status}'))).toList(),onChanged:(v)=>driverId=v),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('إلغاء')),FilledButton(onPressed:driverId==null?null:()async{await widget.api.assignOrder(order.id,driverId!); if(c.mounted)Navigator.pop(c);},child:const Text('تعيين'))])); await load();}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('الطلبات'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh)),IconButton(onPressed:createOrder,icon:const Icon(Icons.add))]),body:loading?const Center(child:CircularProgressIndicator()):ListView.builder(itemCount:orders.length,itemBuilder:(c,i){final o=orders[i];return Card(child:ListTile(title:Text('#${o.id} ${o.customerName}'),subtitle:Text('سعر ${o.foodPrice} + توصيل ${o.deliveryFee} = ${o.totalPrice}\nالحالة ${o.status} | المندوب ${o.driverName??'غير معين'}'),trailing:TextButton(onPressed:()=>assign(o),child:const Text('تعيين'))));}));}
