import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../models/app_models.dart';
import '../services/api_service.dart';

class ReportsScreen extends StatefulWidget{final ApiService api; const ReportsScreen({super.key,required this.api}); @override State<ReportsScreen> createState()=>_ReportsScreenState();}
class _ReportsScreenState extends State<ReportsScreen>{List<DriverRow> drivers=[];DriverRow? selected;Map<String,dynamic>? report;final amount=TextEditingController(text:'0');String date=DateFormat('yyyy-MM-dd').format(DateTime.now().toUtc());bool loading=true;
 @override void initState(){super.initState();load();}
 Future<void>load()async{final d=await widget.api.drivers();drivers=(d['drivers'] as List).map((e)=>DriverRow.fromJson(Map<String,dynamic>.from(e))).toList();selected=selected??(drivers.isEmpty?null:drivers.first);if(selected!=null){final r=await widget.api.driverReport(selected!.id,date);report=r['report'];amount.text='${report!['totals']['expected_return_to_restaurant']}';}setState(()=>loading=false);} 
 Future<void>closeSettlement()async{if(selected==null)return;await widget.api.closeSettlement(selected!.id,date,int.parse(amount.text));if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم إغلاق المحاسبة')));await load();}
 @override Widget build(BuildContext context){final t=report?['totals'];return Scaffold(appBar:AppBar(title:const Text('التقارير والمحاسبة'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[DropdownButtonFormField<DriverRow>(value:selected,items:drivers.map((d)=>DropdownMenuItem(value:d,child:Text(d.name))).toList(),onChanged:(v){setState(()=>selected=v);load();},decoration:const InputDecoration(labelText:'المندوب')),TextField(decoration:const InputDecoration(labelText:'التاريخ UTC yyyy-mm-dd'),controller:TextEditingController(text:date),onChanged:(v)=>date=v),const SizedBox(height:12),if(t!=null)Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('عدد الطلبات: ${t['order_count']}'),Text('أسعار الطلبات: ${t['total_food_price']}'),Text('أجور التوصيل: ${t['total_delivery_fee']}'),Text('المبلغ الكاش الذي يجب تسليمه كاملًا للمطعم: ${t['expected_return_to_restaurant']}'),Text('عمولة المندوب قبل العقوبة: ${t['gross_driver_commission']}'),Text('عدد العقوبات: ${t['penalty_count']} | وقتها: ${t['total_penalty_minutes']} دقيقة'),Text('إجمالي الخصم: ${t['total_penalty_reduction']}'),Text('العمولة النهائية التي يدفعها المطعم للمندوب: ${t['final_driver_commission']}',style:const TextStyle(fontWeight:FontWeight.bold)),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'المبلغ الذي سلّمه المندوب للمطعم')),FilledButton(onPressed:closeSettlement,child:const Text('إغلاق محاسبة اليوم'))])))]));}
}
