import 'package:flutter/material.dart';
import '../services/api_service.dart';

class SettingsScreen extends StatefulWidget{final ApiService api; const SettingsScreen({super.key,required this.api}); @override State<SettingsScreen> createState()=>_SettingsScreenState();}
class _SettingsScreenState extends State<SettingsScreen>{Map<String,dynamic>? s; bool loading=true; final ctrls=<String,TextEditingController>{};
 @override void initState(){super.initState(); load();}
 Future<void> load()async{final d=await widget.api.settings(); s=Map<String,dynamic>.from(d['settings']); for(final k in ['restaurant_name','restaurant_lat','restaurant_lng','geofence_radius_meters','average_return_speed_kmh','return_buffer_minutes','minimum_return_minutes','fixed_commission_amount','commission_delivery_fee_percent','penalty_percent','penalty_duration_minutes']){ctrls[k]=TextEditingController(text:'${s![k]}');} setState(()=>loading=false);} 
 num n(String k)=>num.parse(ctrls[k]!.text); int i(String k)=>int.parse(ctrls[k]!.text);
 Future<void> save()async{await widget.api.updateSettings({'restaurant_name':ctrls['restaurant_name']!.text,'restaurant_lat':n('restaurant_lat'),'restaurant_lng':n('restaurant_lng'),'geofence_radius_meters':i('geofence_radius_meters'),'average_return_speed_kmh':n('average_return_speed_kmh'),'return_buffer_minutes':i('return_buffer_minutes'),'minimum_return_minutes':i('minimum_return_minutes'),'commission_type':s!['commission_type'],'fixed_commission_amount':i('fixed_commission_amount'),'commission_delivery_fee_percent':n('commission_delivery_fee_percent'),'penalty_percent':n('penalty_percent'),'penalty_duration_minutes':i('penalty_duration_minutes'),'auto_penalty_enabled':s!['auto_penalty_enabled']==1,'require_manager_approval_for_penalty':s!['require_manager_approval_for_penalty']==1,'penalty_enabled':s!['penalty_enabled']==1}); if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم الحفظ')));}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('إعدادات المطعم')),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[
  _f('restaurant_name','اسم المطعم'),_f('restaurant_lat','Latitude'),_f('restaurant_lng','Longitude'),_f('geofence_radius_meters','نطاق الرجوع للمطعم بالمتر'),_f('average_return_speed_kmh','متوسط سرعة الرجوع كم/س'),_f('return_buffer_minutes','وقت السماح الإضافي بالدقائق'),_f('minimum_return_minutes','أقل وقت رجوع مسموح'),
  DropdownButtonFormField<String>(value:s!['commission_type'],decoration:const InputDecoration(labelText:'نوع العمولة'),items:const [DropdownMenuItem(value:'fixed',child:Text('مبلغ ثابت')),DropdownMenuItem(value:'delivery_fee_percent',child:Text('نسبة من أجرة التوصيل')),DropdownMenuItem(value:'daily_salary_plus_per_order',child:Text('راتب يومي + لكل طلب')),DropdownMenuItem(value:'zone_fixed',child:Text('حسب المنطقة'))],onChanged:(v)=>setState(()=>s!['commission_type']=v)),
  _f('fixed_commission_amount','العمولة الثابتة'),_f('commission_delivery_fee_percent','نسبة المندوب من التوصيل %'),SwitchListTile(value:s!['penalty_enabled']==1,onChanged:(v)=>setState(()=>s!['penalty_enabled']=v?1:0),title:const Text('تفعيل العقوبات')),SwitchListTile(value:s!['auto_penalty_enabled']==1,onChanged:(v)=>setState(()=>s!['auto_penalty_enabled']=v?1:0),title:const Text('تطبيق العقوبة تلقائيًا')),SwitchListTile(value:s!['require_manager_approval_for_penalty']==1,onChanged:(v)=>setState(()=>s!['require_manager_approval_for_penalty']=v?1:0),title:const Text('تحتاج موافقة المدير')), _f('penalty_percent','نسبة الخصم عند العقوبة %'),_f('penalty_duration_minutes','مدة العقوبة بالدقائق'),FilledButton(onPressed:save,child:const Text('حفظ الإعدادات'))]));
 Widget _f(String k,String label)=>TextField(controller:ctrls[k],keyboardType:TextInputType.number,decoration:InputDecoration(labelText:label));}
